export const MOCK_ASSOCIATIONS = [
  {
    id: '550e8400-e29b-41d4-a716-446655440000',
    name: 'Croix-Rouge Française',
    slug: 'croix-rouge-france',
    description: 'Humanitaire, solidarité, aide d\'urgence et accompagnement social.',
    logoUrl: '🔴',
    status: 'APPROVED' as const,
    stripeConnectAccountId: 'acct_stripe_001',
    stripeOnboardingComplete: true,
    onChainRegistered: true,
    approvedAt: new Date('2026-01-15').toISOString(),
    createdAt: new Date('2025-12-01').toISOString(),
    updatedAt: new Date('2026-01-15').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    name: 'Médecins du Monde',
    slug: 'medecins-du-monde',
    description: 'Accès aux soins et prévention sanitaire pour les populations vulnérables.',
    logoUrl: '🏥',
    status: 'APPROVED' as const,
    stripeConnectAccountId: 'acct_stripe_002',
    stripeOnboardingComplete: true,
    onChainRegistered: true,
    approvedAt: new Date('2026-01-10').toISOString(),
    createdAt: new Date('2025-12-05').toISOString(),
    updatedAt: new Date('2026-01-10').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    name: 'Greenpeace France',
    slug: 'greenpeace-france',
    description: 'Protection de l\'environnement et des océans par la campagne et l\'action.',
    logoUrl: '🌍',
    status: 'APPROVED' as const,
    stripeConnectAccountId: 'acct_stripe_003',
    stripeOnboardingComplete: true,
    onChainRegistered: false,
    approvedAt: new Date('2026-01-05').toISOString(),
    createdAt: new Date('2025-11-20').toISOString(),
    updatedAt: new Date('2026-01-05').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    name: 'Unicef France',
    slug: 'unicef-france',
    description: 'Protection de l\'enfance et droits des enfants à travers le monde.',
    logoUrl: '👶',
    status: 'APPROVED' as const,
    stripeConnectAccountId: 'acct_stripe_004',
    stripeOnboardingComplete: true,
    onChainRegistered: true,
    approvedAt: new Date('2025-12-20').toISOString(),
    createdAt: new Date('2025-11-01').toISOString(),
    updatedAt: new Date('2025-12-20').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440004',
    name: 'Action Contre la Faim',
    slug: 'action-contre-faim',
    description: 'Lutte contre la malnutrition et insécurité alimentaire dans le monde.',
    logoUrl: '🍽️',
    status: 'APPROVED' as const,
    stripeConnectAccountId: 'acct_stripe_005',
    stripeOnboardingComplete: true,
    onChainRegistered: true,
    approvedAt: new Date('2025-12-15').toISOString(),
    createdAt: new Date('2025-10-15').toISOString(),
    updatedAt: new Date('2025-12-15').toISOString(),
  },
];
